apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-09-21T15:01:19Z"
  name: kafka-service
  namespace: default
  resourceVersion: "80592"
  selfLink: /api/v1/namespaces/default/services/kafka-service
  uid: aabdd340-dc80-11e9-8094-42010a800247
spec:
  ports:
  - name: client
    port: 9092
    protocol: TCP
    targetPort: kafka
  selector:
    app: kafka
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-09-21T15:01:19Z"
  name: kafka-headless
  namespace: default
  resourceVersion: "80595"
  selfLink: /api/v1/namespaces/default/services/kafka-headless
  uid: ab10724b-dc80-11e9-8094-42010a800247
spec:
  clusterIP: None
  ports:
  - name: client
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2019-09-16T08:12:39Z"
  generation: 1
  labels:
    app: kafka
  name: kafka
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-headless
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka
    spec:
      containers:
      - command:
        - sh
        - -exc
        - |
          unset KAFKA_PORT && \
          export KAFKA_BROKER_ID=${HOSTNAME##*-} && \
          export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-service:9092 && \
          exec /etc/confluent/docker/run
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181
        - name: KAFKA_LOG_DIRS
          value: /opt/kafka/data/logs
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "10485760"
        - name : KAFKA_PRODUCER_MAX_REQUEST_SIZE
          value: "10485760"
        - name: KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES
          value: "10485760"
        - name: CONNECT_PRODUCER_MAX_REQUEST_SIZE
          value: "10485760"
        - name: CONNECT_CONSUMER_MAX_PARTITION_FETCH_BYTES
          value:  "10485760"
        image: confluentinc/cp-kafka:4.0.0
        imagePullPolicy: IfNotPresent
        name: kafka
        ports:
        - containerPort: 9092
          name: kafka
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: kafka-5b7c4fb547
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: kafka-5b7c4fb547
  updatedReplicas: 1
